apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: llm-demo
spec:
  type: NodePort  # Use LoadBalancer if you're on a cloud that supports it
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      # If using NodePort, you can optionally specify the nodePort:
      # nodePort: 30000